import GoogleAnalytics from "../components/analytics/GoogleAnalytics"
import { Analytics } from "@vercel/analytics/react"

export const metadata = {
  title: 'NCA Parts🔩',
  description: 'Generated by Next.js', 
  icons: {
    icon: "/favicon.ico"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_MEASUREMENT_ID="GTM-NP97WZ33"/>
      <body>
        {children}
        <Analytics/>
      </body>
    </html>
  )
}
